import type { Skill } from "@/@types/opportunity.types";

export const skillOptions: Skill[] = [
  { id: 1, name: "Futebol de Campo" },
  { id: 2, name: "Futsal" },
  { id: 3, name: "Beach Soccer" },
  { id: 4, name: "Futebol Society" },
  { id: 5, name: "Goleiro" },
  { id: 6, name: "Defesa" },
  { id: 7, name: "Meio-campo" },
  { id: 8, name: "Ataque" },
  { id: 9, name: "Capitania" },
  { id: 10, name: "Liderança" },
  { id: 11, name: "Trabalho em Equipe" },
  { id: 12, name: "Disciplina" },
  { id: 13, name: "Resistência Física" },
  { id: 14, name: "Velocidade" },
  { id: 15, name: "Técnica Individual" },
  { id: 16, name: "Visão de Jogo" },
  { id: 17, name: "Finalização" },
  { id: 18, name: "Cruzamentos" },
  { id: 19, name: "Passes" },
  { id: 20, name: "Marcação" },
  { id: 21, name: "Cobrança de Falta" },
  { id: 22, name: "Penalti" },
  { id: 23, name: "Arbitragem" },
  { id: 24, name: "Treinamento" },
  { id: 25, name: "Preparação Física" },
  { id: 26, name: "Nutrição Esportiva" },
  { id: 27, name: "Fisioterapia" },
  { id: 28, name: "Análise Tática" },
  { id: 29, name: "Scouting" },
  { id: 30, name: "Gestão Esportiva" },
  { id: 31, name: "Marketing Esportivo" },
  { id: 32, name: "Mídia Esportiva" },
  { id: 33, name: "Transmissão Esportiva" },
  { id: 34, name: "Fotografia Esportiva" },
];

export const locationOptions = [
  "São Paulo - SP",
  "Rio de Janeiro - RJ",
  "Belo Horizonte - MG",
  "Santos - SP",
  "Remoto",
  "Porto Alegre - RS",
  "Brasília - DF",
  "Curitiba - PR",
  "Salvador - BA",
  "Recife - PE",
];
